### ISSUE TITLE
Content list block display bug

### ISSUE THREAD

**Issue by itkg-bponchaux** [open-orchestra/open-orchestra-front-bundle#133]
I've created in back-office a new content-type (A content with a text input, a text area and a media field). I've also created one content of this type.  On a page i've added a content list block and i've chosen for content type the new type.

But when i check the display on front, the contents who are displayed are not from the content-type i've selected but from another one

My version of the front bundle is dev-master

**Comment by veolys-nanne** [comment]
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/187
