### ISSUE TITLE
'path' twig helper does not generate relative path for node routes

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-front-bundle#151]
Symfony offers two helpers that can be used to generate urls inside a twig template : `path` and `url`. `path` is made to generate a path relative to the domain (e.g. `/my/route/`). When using it to generate a node route, it generates an absolute path (e.g. `//my.domain.com/my/route/`).

**Comment by alavieille** [comment]
Have you always the bug ? because i test on the branch master a function url and path (with option relative true and false) work correctly and with and without parameter siteAlias.

If you have always the bug can you give context

**Comment by raphaelcarles** [comment]
@itkg-canne : is this issue is still relevant ?

**Comment by ghost** [comment]
It seems OK now.
