### ISSUE TITLE
BlockController renders a full page when a 404 error occurs in ESI mode

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-front-bundle#152]
When a 404 error occurs during block rendering, in ESI mode,  `BlockController` renders the full 404 custom page instead of just a fragment. It means that the master request will include a page (`html + head & body`) inside the page, which is not correct.
The `KernelExceptionSubscriber` should, at least, only render the 404 custom page if `Event::isMasterRequest()`.
It can also be possible to add a new subscriber which renders the error only as a page fragment when request type is `HttpKernelInterface::SUB_REQUEST`.

**Comment by alavieille** [comment]
This is fixed in this PR 
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/192
https://github.com/open-orchestra/open-orchestra-docs/pull/232

Thanks
