### ISSUE TITLE
Unable to correctly use sessions on blocks in ESI mode

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-front-bundle#153]
When enabling ESI on server, blocks are rendered by a sub-request, and so are not able to create a PHP Session as the "Set-Cookie" header will not be send to the end-user.
To correctly handle sessions, there are 2 solutions :
1 - render the corresponding block without using ESI, so it will be able to change the master response,
2 - load the block (or just the critical part of it) using an ajax request.

For the first solution, it could be simpler to directly have the ability to define rendering options of each block (like "esi=false"). In this case, the VCL configuration needs to be updated to not remove the session cookie on master request.

The second solution is easy to implement as it can be done using the base BlockController of Open Orchestra.

**Comment by ngilain** [comment]
It seems to be a project problem. For now we can only advise you to use an ajax call that will not be cached by your reverse proxy.

**Comment by ghost** [comment]
It is what we have done, but by doing this, we do not follow "unobtrusive javascript" guidelines anymore.
