### ISSUE TITLE
Sitemap generation leads to Fatal error

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-front-bundle#155]
The console command orchestra:sitemaps:generate cannot be executed as of 1.1-RC.

It seems that the serializer service alias is no longer the native one from Symfony but is instead an alias for jms_serializer (defined in the JMSSerializerBundle), leading to the following error :

```
Catchable Fatal Error: Argument 3 passed to
OpenOrchestra\FrontBundle\Manager\SitemapManager::__construct() must be
an instance of Symfony\Component\Serializer\SerializerInterface,  
instance of JMS\Serializer\Serializer given
```

**Comment by alavieille** [comment]
On branch master, we haven't problem with SerializerInterface but i fix a bug on this command, in this pull request https://github.com/open-orchestra/open-orchestra-front-bundle/pull/158
