### ISSUE TITLE
NonExistingSiteException thrown instead of NodeNotFoundException

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-front-bundle#166]
When I trying to access to an URL on FO website that matches the website alias but does not corresponds a valid published node, a `NonExistingSiteException` (with http code 500) is thrown instead of `NodeNotFoundException` (with http code 404).

This error appeared in 1.1 : http://demo.openorchestra.1-1.inte/ThisNodeDoesNotExists
It was correct on 1.0 : http://demo.openorchestra.1-0.inte/ThisNodeDoesNotExists

**Comment by ngilain** [comment]
This is fixed on both 1.2 and 1.1 versions:
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/585
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/218
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/584
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/217
