### ISSUE TITLE
SiteManager informations are not correct in error node rendering

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-front-bundle#194]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question
## Description

In error node rendering context (node rendered by `OpenOrchestra\FrontBundle\EventSubscriber\KernelExceptionSubscriber::getCustom404Html()`), informations returned by the SiteManager are not correct. Language seems to be a default value (server locale ?) ans siteId is empty. Any block that need this kind of information cannot be rendered correctly.

I also notice that the user token we use in our website to check authentication state is not initialized.

**Comment by alavieille** [comment]
This issue isn't longer valid with 2.0
